use heck::ToUpperCamelCase;
use itertools::Itertools;
use std::ffi::OsStr;
use std::path::Path;
use std::{fs, io};

fn main() {
    println!("cargo:rerun-if-changed=src/action/include.rs");
    println!("cargo:rerun-if-changed=src/action/include/");

    let actions = fs::read_dir("src/action/include/")
        .unwrap()
        .into_iter()
        .map(|p| p.unwrap().path())
        .filter(|p| p.is_file())
        .filter(|p| p.extension().unwrap_or(OsStr::new("")).to_str() == Some("rs"))
        .map(|p| {
            p.with_extension("")
                .file_name()
                .unwrap()
                .to_str()
                .unwrap()
                .to_string()
        })
        .sorted()
        .collect_vec();

    let stateful_actions = actions
        .clone()
        .into_iter()
        .filter(|n| {
            fs::read_to_string(
                Path::new("src/action/include/").join(Path::new(n).with_extension("rs")),
            )
            .unwrap()
            .contains(&format!("Stateful{}", n.to_upper_camel_case()))
        })
        .collect_vec();

    let content = format!(
        "\
        // This file is automatically generated by the crate build script.\n\
        // DO NOT MODIFY THIS FILE MANUALLY! CHANGES WILL BE REVERTED.\n\n\
        include_actions!(\n{}\n);\n\n\
        include_stateful_actions!(\n{}\n);\n\
        ",
        actions
            .into_iter()
            .map(|n| format!("    {n},"))
            .collect::<Vec<_>>()
            .join("\n"),
        stateful_actions
            .into_iter()
            .map(|n| format!("    {n},"))
            .collect::<Vec<_>>()
            .join("\n"),
    );

    let path = "src/action/include.rs";
    match fs::read_to_string(path) {
        Ok(current) if current == content => {}
        _ => {
            fs::write(path, content)
                .expect("Failed to generate src/action/include.rs automatically!");
        }
    }
}
