// This file is automatically generated by the crate build script.
// DO NOT MODIFY THIS FILE MANUALLY! CHANGES WILL BE REVERTED.

include_actions!(
    audio,
    counter,
    fixation,
    image,
    instruction,
    key_logger,
    nop,
    question,
    simple,
    stream,
    video,
);

include_stateful_actions!(
    audio,
    counter,
    image,
    instruction,
    key_logger,
    nop,
    question,
    stream,
    video,
);
