// This file is automatically generated by the crate build script.
// DO NOT MODIFY THIS FILE MANUALLY! CHANGES WILL BE REVERTED.

include_actions!(
    audio,
    counter,
    delayed,
    event,
    fixation,
    image,
    instruction,
    key_logger,
    nil,
    par,
    question,
    reaction,
    seq,
    stream,
    template,
    timeout,
    video,
    wait,
);

include_stateful_actions!(
    audio,
    counter,
    delayed,
    event,
    image,
    instruction,
    key_logger,
    nil,
    par,
    question,
    reaction,
    seq,
    stream,
    timeout,
    video,
    wait,
);
